{% set name = "ssh2-python" %}
{% set version = "0.21.0" %}
{% set sha256 = "c55fc1356de84b11496959d7dd062ee48a3488d4759f53909e5de8f2ed8091e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  script:
    - SYSTEM_LIBSSH2=1 python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - libssh2 1.8.*
    - toolchain3
  run:
    - libssh2 1.8.*

test:
  imports:
    - ssh2.session

about:
  home: http://github.com/ParallelSSH/ssh2-python
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: Super fact SSH library. Based on libssh2.

  description: |
    Super fast SSH2 protocol library.

    ssh2-python provides Python bindings for libssh2.

    Its only dependency is the libssh2 library.
  dev_url: https://github.com/ParallelSSH/ssh2-python

extra:
  recipe-maintainers:
    - pkittenis
