{% set name = "ssh2-python" %}
{% set version = "1.1.2.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c39b9f11fd0e2a7422480aa61b8787c444b26a402907c9e2798767763763bb7c

build:
  skip: true  # [win]
  number: 2
  script:
    - SYSTEM_LIBSSH2=1 pip install . -vv
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - libssh2
    - setuptools
  run:
    - python

test:
  imports:
    - ssh2.session
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/ParallelSSH/ssh2-python
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'Super fast SSH library. Based on libssh2.'

  description: |
    Super fast SSH2 protocol library.

    ssh2-python provides Python bindings for libssh2.

    Its only dependency is the libssh2 library.
  dev_url: https://github.com/ParallelSSH/ssh2-python

extra:
  recipe-maintainers:
    - pkittenis
    - thewchan
