{% set name = "ssh2-python" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af89e80c3203e7829b24eea688eaf5c5e279071aed1882238b4f44ec2144e7c5

build:
  skip: true  # [win]
  number: 2
  script:
    - SYSTEM_LIBSSH2=1 pip install . -vv
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libssh2
  run:
    - python

test:
  imports:
    - ssh2.session

about:
  home: http://github.com/ParallelSSH/ssh2-python
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'Super fast SSH library. Based on libssh2.'

  description: |
    Super fast SSH2 protocol library.

    ssh2-python provides Python bindings for libssh2.
    
    Its only dependency is the libssh2 library.
  dev_url: https://github.com/ParallelSSH/ssh2-python

extra:
  recipe-maintainers:
    - pkittenis
    - thewchan
