appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Zo9qRKNkHEsp8PfG5wb0Lzgzn6AUWrezjq8UqeZY/yZvtpFFB9eI4O/jSJBkDqMd0p/ZEhNXXGevXx5TBlQ0G0TwOhdYWwwtlbgw8M3XSjUA65ewlI+yqVuo/3FNPiMY+WXX1C879Sq47IXuxBzmXUyg0TK/SCQ1HMfkcdcLCW9HSANkAVF0MQsfHj6KZy8axFgp98P6v5hhmGxJezGyr5oc3kj65u9HZcFzg177K9ctJ8wgZo/efCOIAdOjRTo8DXXSh1IfZjSsMTrIo1ui7auKKfWR7cNGOoON4n2qFKJwOhNOiN6Zfl9vnI9TEd8SyKOxQ6HD2egDvxKg6ku0nGhmWkzd+AvRHEf1Dy11w6RwvPIU4WBf/Btb2RioIAUwnL8Msyko413vICl5ad3Kfw8rURL3bU6VxKJ7Ueof6s1TznVYqcP9jjfQhqUVELqLJezIyIx3fBlnRFJzejp/SszYSuhAyJQ4/D7s9Y/Qt86rtjGrABfRKlvbxxbBS10QiSr1r/kod4+rFCM4oqI56zlTuISBWG80dmQhFIFVWOa/dPjVNDbIpHSRT0xz8fiN7Dp5HSpBnyYWq+0azZriRmYq62yJWvnutw3R81OzI4Q1dqs5EnAAgxIP3jFuZC4Ig0N/vTXxTX3RrvbxadDZ6fCmyg1lVBnZ8idDWCSg+sQ=}
